### PR TITLE
Fetch nutritional information

### PR DESCRIPTION
**Pull request by talwrii**
I mostly put this here because I wanted to use your login logic and I think it makes sense for mynetdiary scraping code to live in one place.

I had to tweak the weight fetching logic a little work (on my box beautiful soup was not finding the script element).

Additionally I've done a little clean up to make room for my changes. See what you think, experience suggests that one persons "clean" might be another's boiler plate, obfuscation and needless generality.

### CODE REVIEW

**Comment by tnarik** [comment]
I'll take a look when I have some spare time. my original goal was just
being able to get weight data for plotting and as a backup, never thought
anyone would use any of this. :)

**Comment by talwrii** [comment]
Cool cool. 

So if you aren't massively motivated by this it might make sense for me to just maintain my own fork and/or rename this to something else (referencing your repository) because otherwise I might keep pushing diffs at you that you don't care about!

I tend to do pull requests before forking on the grounds that fewer slightly different repositories is good thing, and just to give people a heads-up about code reuse.

**Comment by tnarik** [comment]
not going to apply as the tool i meant to be as simple as possible.

**Comment by talwrii** [comment]
Whoops! Looks like I pushed those changes to the wrong branch.  I've rolled back those changes with a force push.

As a quick heads-up, I've been extending your tool quite a bit for my own personal uses. I've added the ability to search the food database, insert food items, display food items for a day etc. I may well release this as something like *mynetdiary-cli* referencing you in 
the README according to your preferences.

**Comment by talwrii** [comment]
It's mostly the login code that has been of use to me. My experience with screen scraping is that this is quite fiddly to implement first time around.

**Pull request closed without merging**
